/**
 * Word API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WordDTO } from './wordDTO';


export interface BatchWordUpdateDTO { 
    updatedWords?: Array<WordDTO>;
    deletedWordIds?: Array<string>;
}

