/**
 * Word API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface LessonDTO {
  id: string;
  lessonName: string;
  description: string;
  shared: boolean;
  language: string;
  score: number;
  wordCount: number;
}
