/**
 * Word API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TranslationDTO { 
    text: string;
    sourceLang: string;
    targetLang: string;
}

