openapi: 3.0.0
info:
  title: Word API
  version: 1.0.0
servers:
  - url: /api
tags:
  - name: User
    description: Users own Lessons
  - name: Lesson
    description: Lessons own Words
  - name: Word
    description: Words are lowest entities

paths:
  /users:
    post:
      summary: Create a user
      tags:
        - User
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppUserDTO'
      responses:
        '200':
          description: User created
          content:
            application/json:
              schema:
                type: string
                format: uuid
        '400':
          description: Invalid input
        '409':
          description: User already exists

    put:
      summary: Update a user
      parameters:
        - $ref: '#/components/parameters/UserIdHeader'
      tags:
        - User
      operationId: updateUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppUserDTO'
      responses:
        '201':
          description: User updated
        '400':
          description: Invalid input
        '409':
          description: User already exists
    delete:
      summary: Delete a user
      parameters:
        - $ref: '#/components/parameters/UserIdHeader'
      tags:
        - User
      operationId: deleteUser
      responses:
        '204':
          description: User deleted

  /users/login:
    post:
      summary: Login a user
      tags:
        - User
      operationId: loginUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppUserDTO'
      responses:
        '200':
          description: User logged in
          content:
            application/json:
              schema:
                type: string
                format: uuid
        '400':
          description: Invalid input
        '401':
          description: Unauthorized access

  /users/me/lessons:
    get:
      summary: Get all lessons of logged in user
      tags:
        - User
      operationId: getLessonsOfLoggedInUser
      parameters:
        - $ref: '#/components/parameters/UserIdHeader'
      responses:
        '200':
          description: Lessons of logged in user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LessonDTO'
        '401':
          description: User id missing or invalid

  /lessons:
    post:
      summary: Create a new lesson
      tags:
        - Lesson
      operationId: createLesson
      parameters:
        - $ref: '#/components/parameters/UserIdHeader'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewLessonDTO'
      responses:
        '200':
          description: Lesson created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LessonDTO'
        '400':
          description: Invalid input
        '401':
          description: User id missing or invalid

    put:
      summary: Update a lesson
      tags:
        - Lesson
      operationId: updateLesson
      parameters:
        - $ref: '#/components/parameters/UserIdHeader'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LessonDTO'
      responses:
        '201':
          description: Lesson created
        '400':
          description: Invalid input
        '401':
          description: User id missing or invalid


  /lessons/{lessonId}:
    delete:
      summary: Delete a lesson
      tags:
        - Lesson
      operationId: deleteLesson
      parameters:
        - $ref: '#/components/parameters/UserIdHeader'
        - name: lessonId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Lesson deleted
        '401':
          description: User id missing or invalid

  /lessons/{lessonId}/copy:
    post:
      summary: Copy a shared lesson
      tags:
        - Lesson
      operationId: copySharedLesson
      parameters:
        - $ref: '#/components/parameters/UserIdHeader'
        - name: lessonId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Lesson copied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LessonDTO'
        '401':
          description: User id missing or invalid
        '403':
          description: Unauthorized access to lesson


  /lessons/{lessonId}/words:
    get:
      summary: Get all words of a lesson
      tags:
        - Lesson
      operationId: getWordsByLessonId
      parameters:
        - $ref: '#/components/parameters/UserIdHeader'
        - name: lessonId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Words of the lesson
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WordDTO'
        '401':
          description: User id missing or invalid
        '403':
          description: Unauthorized access to lesson

    post:
      summary: Create new words in a lesson
      parameters:
        - $ref: '#/components/parameters/UserIdHeader'
        - name: lessonId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      tags:
        - Lesson
      operationId: createWords
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/NewWordDTO'
      responses:
        '201':
          description: Word created

  /words:
    put:
      summary: Update and/or delete words
      parameters:
        - $ref: '#/components/parameters/UserIdHeader'
      tags:
        - Word
      operationId: updateWords
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchWordUpdateDTO'
      responses:
        '204':
          description: Words updated and/or deleted

components:
  schemas:
    WordDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        question:
          type: string
          minLength: 1
          maxLength: 40
          pattern: '^[\p{L} ]+$'
          example: "black dog"
        answer:
          type: string
          minLength: 1
          maxLength: 40
          pattern: '^[\p{L} ]+$'
          example: "černý pes"
        score:
          type: integer
      required:
        - id
        - question
        - answer
        - score

    NewWordDTO:
      type: object
      properties:
        question:
          type: string
          minLength: 1
          maxLength: 40
          pattern: '^[\p{L} ]+$'
          example: "black dog"
        answer:
          type: string
          minLength: 1
          maxLength: 40
          pattern: '^[\p{L} ]+$'
          example: "černý pes"
      required:
        - question
        - answer

    BatchWordUpdateDTO:
      type: object
      properties:
        updatedWords:
          type: array
          items:
            $ref: '#/components/schemas/WordDTO'
        deletedWordIds:
          type: array
          items:
            type: string
            format: uuid

    LessonDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        lessonName:
          type: string
          minLength: 3
          maxLength: 30
          pattern: '^[\p{L} ]+$'
          example: "Podstatná jména"
        description:
          type: string
          minLength: 3
          maxLength: 60
          pattern: '^[\p{L} ]+$'
          example: "V lekci jsou běžná podstatná jména"
        shared:
          type: boolean
      required:
        - id
        - lessonName
        - description
        - shared

    NewLessonDTO:
      type: object
      properties:
        lessonName:
          type: string
          minLength: 3
          maxLength: 30
          pattern: '^[\p{L} ]+$'
          example: "Podstatná jména"
        description:
          type: string
          minLength: 3
          maxLength: 60
          pattern: '^[\p{L} ]+$'
          example: "V lekci jsou běžná podstatná jména"
        shared:
          type: boolean
      required:
        - lessonName
        - description
        - shared

    AppUserDTO:
      type: object
      properties:
        appUserName:
          type: string
          minLength: 3
          maxLength: 20
          pattern: '^[a-zA-Z0-9_]+$'
          example: "john_doe"
        passwordHash:
          type: string
          minLength: 8
          maxLength: 16
          pattern: '^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d@$!%*?&]+$'
          example: "P@ssw0rd123"
      required:
        - appUserName
        - passwordHash

  parameters:
    UserIdHeader:
      name: X-User-Id
      in: header
      required: true
      schema:
        type: string
        format: uuid
