/**
 * Word API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WordDTO { 
    id: string;
    question: string;
    answer: string;
    score: number;
}

