/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.9.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.learn.turnup.apis;

import com.learn.turnup.dto.BatchWordUpdateDTO;
import com.learn.turnup.dto.TranslationDTO;
import com.learn.turnup.dto.WordScoreDTO;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import java.util.List;
import java.util.UUID;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-08-22T18:07:50.748697700+02:00[Europe/Prague]", comments = "Generator version: 7.9.0")
@Validated
@Tag(name = "Word", description = "Words are lowest entities")
public interface WordsApi {

    /**
     * POST /words : Translate word
     *
     * @param translationDTO  (required)
     * @return Word tranlsated (status code 200)
     *         or Invalid input (status code 400)
     */
    @Operation(
        operationId = "translateWord",
        summary = "Translate word",
        tags = { "Word" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Word tranlsated", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = String.class))
            }),
            @ApiResponse(responseCode = "400", description = "Invalid input")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/words",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<String> translateWord(
        @Parameter(name = "TranslationDTO", description = "", required = true) @Valid @RequestBody TranslationDTO translationDTO
    );


    /**
     * PUT /words : Update and/or delete words
     *
     * @param xUserId  (required)
     * @param batchWordUpdateDTO  (required)
     * @return All words successfully updated and/or deleted (status code 204)
     *         or Invalid input (status code 400)
     *         or User ID is not recognized (status code 401)
     *         or Unauthorized access to words (status code 403)
     */
    @Operation(
        operationId = "updateWords",
        summary = "Update and/or delete words",
        tags = { "Word" },
        responses = {
            @ApiResponse(responseCode = "204", description = "All words successfully updated and/or deleted"),
            @ApiResponse(responseCode = "400", description = "Invalid input"),
            @ApiResponse(responseCode = "401", description = "User ID is not recognized"),
            @ApiResponse(responseCode = "403", description = "Unauthorized access to words")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/words",
        consumes = { "application/json" }
    )
    
    ResponseEntity<Void> updateWords(
        @NotNull @Parameter(name = "X-User-Id", description = "", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "X-User-Id", required = true) UUID xUserId,
        @Parameter(name = "BatchWordUpdateDTO", description = "", required = true) @Valid @RequestBody BatchWordUpdateDTO batchWordUpdateDTO
    );


    /**
     * PUT /words/scores : Update words&#39; scores
     *
     * @param xUserId  (required)
     * @param wordScoreDTO  (required)
     * @return All words&#39; scores successfully updated (status code 204)
     *         or Invalid input (status code 400)
     *         or User ID is not recognized (status code 401)
     *         or Unauthorized access to words (status code 403)
     */
    @Operation(
        operationId = "updateWordsScores",
        summary = "Update words' scores",
        tags = { "Word" },
        responses = {
            @ApiResponse(responseCode = "204", description = "All words' scores successfully updated"),
            @ApiResponse(responseCode = "400", description = "Invalid input"),
            @ApiResponse(responseCode = "401", description = "User ID is not recognized"),
            @ApiResponse(responseCode = "403", description = "Unauthorized access to words")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/words/scores",
        consumes = { "application/json" }
    )
    
    ResponseEntity<Void> updateWordsScores(
        @NotNull @Parameter(name = "X-User-Id", description = "", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "X-User-Id", required = true) UUID xUserId,
        @Parameter(name = "WordScoreDTO", description = "", required = true) @Valid @RequestBody List<@Valid WordScoreDTO> wordScoreDTO
    );

}
