/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.9.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.learn.turnup.apis;

import java.util.UUID;

import com.learn.turnup.dto.BatchWordUpdateDTO;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-06-03T14:28:36.823820900+02:00[Europe/Prague]", comments = "Generator version: 7.9.0")
@Validated
@Tag(name = "Word", description = "Words are lowest entities")
public interface WordsApi {

    /**
     * PATCH /words : Update and/or delete words
     *
     * @param xUserId  (required)
     * @param batchWordUpdateDTO  (required)
     * @return Words updated and/or deleted (status code 204)
     */
    @Operation(
        operationId = "updateWords",
        summary = "Update and/or delete words",
        tags = { "Word" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Words updated and/or deleted")
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = "/words",
        consumes = { "application/json" }
    )
    
    ResponseEntity<Void> updateWords(
        @NotNull @Parameter(name = "X-User-Id", description = "", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "X-User-Id", required = true) UUID xUserId,
        @Parameter(name = "BatchWordUpdateDTO", description = "", required = true) @Valid @RequestBody BatchWordUpdateDTO batchWordUpdateDTO
    );

}
